# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"

# Anaconda information comes from https://gist.github.com/dan-blanchard/7045057
# Setup anaconda
before_install:
  - sudo apt-get update
  # You may want to periodically update this, although the conda update
  # conda line below will keep everything up-to-date.  We do this
  # conditionally because it saves us some downloading if the version is
  # the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
# Install packages
install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda install -n test-environment pip
  - conda install -n test-environment atlas numpy scipy matplotlib nose cython
  - source activate test-environment
  - pip install pint mpmath bunch mock
  - python setup.py install
 
# Run test
script:
  - nosetests